name: Build QMK firmware

on:
  - workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    name: QMK Userspace
    uses: sigprof/qmk_userspace_test/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master
