name: Build QMK firmware

on:
  - workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    name: QMK Userspace
    uses: qmk/qmk_firmware/.github/workflows/qmk_userspace_build.yml@qmk-userspace
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master
